spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/person-service?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: test
    driverClassName: org.mariadb.jdbc.Driver

  flyway:
    user: root
    password: test
    baselineOnMigrate: true
  jpa:
    showSql: true