CREATE TABLE addresses (
   id CHAR(36) NOT NULL,
   type VARCHAR(20) NOT NULL,
   value VARCHAR(255) NOT NULL,
   is_primary BIT(1) NOT NULL,
   region_id CHAR(36) NOT NULL,
   person_id CHAR(36) NOT NULL,
   PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE contacts (
   id CHAR(36) NOT NULL,
   type VARCHAR(255) NOT NULL,
   value VARCHAR(255) NOT NULL,
   is_primary BIT(1) NOT NULL,
   person_id CHAR(36) NOT NULL,
   PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE documents (
   id CHAR(36) NOT NULL,
   type VARCHAR(20) NOT NULL,
   value VARCHAR(255) NOT NULL,
   person_id CHAR(36) NOT NULL,
   PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE persons (
   id CHAR(36) NOT NULL,
   first_name VARCHAR(255) NOT NULL,
   last_name VARCHAR(255) NOT NULL,
   middle_name VARCHAR(255) NULL,
   enabled BIT(1) NOT NULL,
   PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE regions (
   id CHAR(36) NOT NULL,
   name VARCHAR(255) NOT NULL,
   PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

ALTER TABLE addresses ADD CONSTRAINT FK_ADDRESS_ON_PERSON FOREIGN KEY (person_id) REFERENCES persons (id);

ALTER TABLE addresses ADD CONSTRAINT FK_ADDRESS_ON_REGION FOREIGN KEY (region_id) REFERENCES regions (id);

ALTER TABLE contacts ADD CONSTRAINT FK_CONTACT_ON_PERSON FOREIGN KEY (person_id) REFERENCES persons (id);

ALTER TABLE documents ADD CONSTRAINT FK_DOCUMENT_ON_PERSON FOREIGN KEY (person_id) REFERENCES persons (id);
